### ISSUE TITLE
'PayFortSDK/PayFortSDK.h' file not found

### ISSUE THREAD

**Issue by mustafaskyer** [zumaawad/react-native-payfort#3]
_Hi @zumaawad , 
first of all I appreciate your work,_

**_XCODE build failed_**
_`'PayFortSDK/PayFortSDK.h' file not found`_
_**file: RCTPayfort.m**_

> _React Native Environment Info:_

> System:
>       OS: macOS 10.14.3
>       Shell: 3.2.57 - /bin/bash
>     Binaries:
>       Node: 11.9.0
>       Yarn: 1.13.0
>       npm: 6.9.0
>       Watchman: 4.9.0 
>     SDKs:
>       iOS SDK:
>         Platforms: iOS 12.2
>     IDEs:
>       Xcode: 10.2.1
>     npmPackages:
>       react: ^16.7.0 => 16.7.0 
>       react-native: ^0.58.5 => 0.58.5 
>     npmGlobalPackages:
>       react-native-cli: 2.0.1

**Comment by ThanhPhat1080** [comment]
Hi @mustafaskir . I got the same issue. Did you found the way to fix it?

**Comment by mustafaskyer** [comment]
Hi @ThanhPhat1080 
for this error, just download the PAYFORT SDK from the offical website, and drag it into your Xcode project as explained in their docs,
but I faced more issues, from the repo itself so,
I had to implement it natively with an ios developer

**Comment by ThanhPhat1080** [comment]
Hi @mustafaskir Thanks for your response. It work for me now. 
I've just create an app with RN-CLI then downloaded PayfortSDK and drap-drop the sdk to `Frameworks`. Then I chose "Copy items if needed" and "Create groups" after drop. 

Continue with 
```bash
yarn add react-native-payfort
react-native link react-native-payfort
```
Then run application.

![AppDelegate_m](https://user-images.githubusercontent.com/17384858/59576538-6a333a80-90ea-11e9-9f3f-d953984c6505.png)

**Comment by mustafaskyer** [comment]
yup, great @ThanhPhat1080 ,
thanks for letting me know :)
